server:
  port: ${SERVER_PORT:8080}

weather-api:
  url: ${WEATHER_API_URL:http://api.weatherapi.com/}
  key: ${WEATHER_API_KEY:6a5bfb7354774e43b1c105914200911}
venues-api:
  url: ${VENUES_API_URL:http://api.foursquare.com/}
  client_id: ${CLIENT_ID:VKTQAU1E4GFURS0U5J1ZYFK5RC0W0T0EQXQ4LBDHSF04CENS}
  client_secret: ${CLIENT_SECRET:1F2A41RPWNAVRBPKELMTT5QGAQ1WJPAIM0R5OSHU52LSDOJU}
  v: ${VERSION:20201010}
route-api:
  url: ${ROUTE_API_URL:https://api.geoapify.com/}
  key: ${ROUTE_API_KEY:827903ca0419402e95e5d8833a5cc40c}
